### ISSUE TITLE
Why are you using STM32 ST-LINK utility and not STM32CubeProgrammer?

### ISSUE THREAD

**Issue by hcet14** [GadgetAngel/BTT_SKR_13_14_14T_SD-DFU-Bootloader#7]
This is just a question!

Hello GadgetAngel,
why are you using STM32 ST-LINK utility and not STM32CubeProgrammer?

Nice job! If I successfully saved my FW, I'll post it here (SKR 2, F429).

Kind regards, hcet14

I'll close this issue after an answer.

**Comment by GadgetAngel** [comment]
You can use either.  I just prefer the ST-LINK utility
